# https://taskfile.dev

version: "3"

tasks:
  default:
    cmds:
      - task --list-all
      - echo $PWD

  new:
    cmds:
      - perl ./bin/gen-new-framework-2016.pl {{.CLI_ARGS}}

  merge-day:
    cmds:
      - perl ./bin/merge-back-2016.pl
      - git push

  01:
    cmds:
      - go run ./2016/01

  02:
    cmds:
      - go run ./2016/02

  03:
    cmds:
      - go run ./2016/03

  04:
    cmds:
      - go run ./2016/04

  05:
    cmds:
      - go run ./2016/05

  06:
    cmds:
      - go run ./2016/06

  07:
    cmds:
      - go run ./2016/07

  08:
    cmds:
      - go run ./2016/08

  09:
    cmds:
      - go run ./2016/09

  10:
    cmds:
      - go run ./2016/10

  11:
    cmds:
      - go run ./2016/11

  12:
    cmds:
      - go run ./2016/12

  13:
    cmds:
      - go run ./2016/13

  14:
    cmds:
      - go run ./2016/14

  15:
    cmds:
      - go run ./2016/15

  16:
    cmds:
      - go run ./2016/16
