# https://taskfile.dev

version: "3"

includes:
  2015: ./2015/Taskfile.yaml
  2016: ./2016/Taskfile.yaml
  2017: ./2017/Taskfile.yaml

vars:
  YEAR: 2017
  LANG: ruby

tasks:
  default:
    desc: list all available tasks
    cmds:
      - task --list-all

  commit0:
    desc: Commit preliminary puzzle data, test framework, etc
    cmds:
      - perl ./bin/commit.pl

  commit1:
    desc: Commit part 1 solution; must specify answer (task commit1 -- ANSWER)
    cmds:
      - perl ./bin/commit.pl 1 {{.CLI_ARGS}}

  commit2:
    desc: Commit part 2 solution; must specify answer (task commit2 -- ANSWER)
    cmds:
      - perl ./bin/commit.pl 2 {{.CLI_ARGS}}

  new:
    desc: Generate branch for new day NN (task new -- NN)
    cmds:
      - perl ./bin/gen-new-framework.pl {{.YEAR}} {{.LANG}} {{.CLI_ARGS}}
