# https://taskfile.dev

version: "3"

tasks:
  default:
    cmds:
      - task --list-all

  new:
    cmds:
      - perl ./bin/gen-new-framework-2015.pl {{.CLI_ARGS}}

  merge-day:
    cmds:
      - perl ./bin/merge-back-2015.pl
      - git push

  01:
    dir: ./2015/01
    cmds:
      - perl ./01.pl

  02:
    dir: ./2015/02
    cmds:
      - perl ./02.pl

  03:
    dir: ./2015/03
    cmds:
      - perl ./03.pl

  04:
    dir: ./2015/04
    cmds:
      - perl ./04.pl

  05:
    dir: ./2015/05
    cmds:
      - perl ./05.pl

  06:
    dir: ./2015/06
    cmds:
      - perl ./06.pl

  07:
    dir: ./2015/07
    cmds:
      - perl ./07.pl

  08:
    dir: ./2015/08
    cmds:
      - perl ./08.pl

  09:
    dir: ./2015/09
    cmds:
      - perl ./09.pl

  10:
    dir: ./2015/10
    cmds:
      - perl ./10.pl

  11:
    dir: ./2015/11
    cmds:
      - perl ./11.pl

  12:
    dir: ./2015/12
    cmds:
      - perl ./12.pl

  13:
    dir: ./2015/13
    cmds:
      - perl ./13.pl

  14:
    dir: ./2015/14
    cmds:
      - perl ./14.pl

  15:
    dir: ./2015/15
    cmds:
      - perl ./15.pl

  16:
    dir: ./2015/16
    cmds:
      - perl ./16.pl

  17:
    dir: ./2015/17
    cmds:
      - perl ./17.pl

  18:
    dir: ./2015/18
    cmds:
      - perl ./18.pl

  19:
    dir: ./2015/19
    cmds:
      - perl ./19.pl

  20:
    dir: ./2015/20
    cmds:
      - perl ./20.pl

  21:
    dir: ./2015/21
    cmds:
      - perl ./21.pl

  22:
    dir: ./2015/22
    cmds:
      - perl ./22.pl

  23:
    dir: ./2015/23
    cmds:
      - perl ./23.pl

  24:
    dir: ./2015/24
    cmds:
      - perl ./24.pl
