# https://taskfile.dev

version: "3"

tasks:
  new:
    cmds:
      - perl ./bin/gen-new-framework.pl {{.CLI_ARGS}}

  01:
    dir: ./2015/01
    cmds:
      - perl ./01.pl

  02:
    dir: ./2015/02
    cmds:
      - perl ./02.pl

  03:
    dir: ./2015/03
    cmds:
      - perl ./03.pl
