# https://taskfile.dev

version: "3"

tasks:
  default:
    cmds:
      - task --list-all

  new:
    cmds:
      - perl ./bin/gen-new-framework-2016.pl {{.CLI_ARGS}}

  merge-day:
    cmds:
      - perl ./bin/merge-back-2016.pl
      - git push

  01:
    cmds:
      - go run ./2016/01
