# https://taskfile.dev

version: "3"

includes:
  # 2015: ./2015/Taskfile.yaml
  2016: ./2016/Taskfile.yaml

vars:
  YEAR: 2016

tasks:
  default:
    cmds:
      - task --list-all

  commit0:
    cmds:
      - perl ./bin/commit.pl

  commit1:
    cmds:
      - perl ./bin/commit.pl 1 {{.CLI_ARGS}}

  commit2:
    cmds:
      - perl ./bin/commit.pl 2 {{.CLI_ARGS}}

  new:
    cmds:
      - perl ./bin/gen-new-framework.pl {{.YEAR}} {{.CLI_ARGS}}

  merge-day:
    cmds:
      - perl ./bin/merge-back.pl {{.YEAR}}
      - git push
