# https://taskfile.dev

version: "3"

includes:
  2015: ./2015/Taskfile.yaml

tasks:
  default:
    cmds:
      - task --list-all

  new:
    cmds:
      - perl ./bin/gen-new-framework-2015.pl {{.CLI_ARGS}}

  merge-day:
    cmds:
      - perl ./bin/merge-back-2015.pl
      - git push
