# https://taskfile.dev

version: "3"

tasks:
  hw:
    dir: ./2017/hw
    cmds:
      - cargo run

  slow:
    internal: true
    cmds:
      - perl ./bin/slow-runner.pl

  01:
    dir: ./2017/01
    cmds:
      - clear
      - cargo run

  02:
    dir: ./2017/02
    cmds:
      - clear
      - cargo run

  03:
    dir: ./2017/03
    cmds:
      - clear
      - cargo run

  04:
    dir: ./2017/04
    cmds:
      - clear
      - cargo run

  05:
    dir: ./2017/05
    cmds:
      - clear
      - cargo run
