# https://taskfile.dev

version: "3"

tasks:
  hw-rust:
    internal: true
    silent: true
    dir: ./2017/hw
    cmds:
      - echo "The Rust way"
      - cargo run
  hw-ruby:
    internal: true
    silent: true
    cmds:
      - echo "------------"
      - echo "The Ruby way"
      - ruby ./2017/hw/hw.rb
  hw:
    cmds:
      - task: hw-rust
      - task: hw-ruby

  slow:
    internal: true
    cmds:
      - perl ./bin/slow-runner.pl

  01:
    dir: ./2017/01
    cmds:
      - clear
      - cargo run

  02:
    dir: ./2017/02
    cmds:
      - clear
      - cargo run

  03:
    dir: ./2017/03
    cmds:
      - clear
      - cargo run

  04:
    dir: ./2017/04
    cmds:
      - clear
      - cargo run

  05:
    dir: ./2017/05
    cmds:
      - clear
      - cargo run

  06:
    dir: ./2017/06
    cmds:
      - clear
      - cargo run

  07:
    dir: ./2017/07
    cmds:
      - ruby 07.rb

  08:
    dir: ./2017/08
    cmds:
      - ruby 08.rb

  09:
    dir: ./2017/09
    cmds:
      - ruby 09.rb
