# https://taskfile.dev

version: "3"

tasks:
  hw:
    dir: ./2017/hw
    cmds:
      - cargo run

  slow:
    internal: true
    cmds:
      - perl ./bin/slow-runner.pl

  test:
    cmds:
      - go test ./2016/lib/**

  01:
    cmds:
      - go run ./2016/01
