# https://taskfile.dev

version: "3"

tasks:
  hw:
    dir: ./2017/hw
    cmds:
      - cargo run

  slow:
    internal: true
    cmds:
      - perl ./bin/slow-runner.pl

  01:
    dir: ./2017/01
    cmds:
      - clear
      - cargo run
