# https://taskfile.dev

version: "3"

tasks:
  hw:
    dir: ./2017/hw
    cmds:
      - cargo run

  slow:
    internal: true
    cmds:
      - perl ./bin/slow-runner.pl

  edit:
    desc: Open specified rust project directly in editor (task commit1 -- NN)
    cmds:
      - code 2017/{{.CLI_ARGS}}

  01:
    dir: ./2017/01
    cmds:
      - clear
      - cargo run

  02:
    dir: ./2017/02
    cmds:
      - clear
      - cargo run

  03:
    dir: ./2017/03
    cmds:
      - clear
      - cargo run

  04:
    dir: ./2017/04
    cmds:
      - clear
      - cargo run

  05:
    dir: ./2017/05
    cmds:
      - clear
      - cargo run

  06:
    dir: ./2017/06
    cmds:
      - clear
      - cargo run

  07:
    dir: ./2017/07
    cmds:
      - clear
      - cargo run
